language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

services:
  - docker

install:
  - mvn clean package docker:build

script: true

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker push pacworx/atp-api

notifications:
  slack: noodle-app:M2sZGPNSvxzvLD4XkaUF4oGI