language: java
jdk:
  - oraclejdk8

services:
  - docker

script:
  - mvn clean package docker:build

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker push pacworx/atp-api