spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/atp
        username: atpuser
        password: askthepeople
        driver-class-name: org.postgresql.Driver
    jackson:
        serialization.write_dates_as_timestamps: false
        mapper.default-view-inclusion: true
    jpa:
      show-sql: false

jwt.secret: ${jwt_appsecret:thisissecret}
jwt.web.secret: ${jwt_websecret:alocaljwtsecret}

email:
  host: ${email_host}
  user: ${email_user}
  password: ${email_password}
  reply-to: no-reply@askthepeople.io
  jwt: ${email_jwt}
  confirmation-url: ${email_confirmation_url:http://localhost:8080/confirm/email?token=}

---

spring:
    profiles: prod
    datasource:
        url: jdbc:postgresql://atp-db/atp
        username: atp-user
        password: mcks89w3jkdlwcmdsklslld