spring:
    application:
      name: atp-api
    datasource:
        url: jdbc:postgresql://localhost:5432/atp
        username: atpuser
        password: askthepeople
        driver-class-name: org.postgresql.Driver
    jackson:
        serialization.write_dates_as_timestamps: false
        mapper.default-view-inclusion: true
    jpa:
      show-sql: false
api.version: @project.version@
jwt:
    secret: thisissecret
    web.secret: alocaljwtsecret
    trade.secret: cnsjdkncvjknvk
fcm.serverkey: null
email:
    host: ${ATP_EMAIL_HOST}
    user: ${ATP_EMAIL_USER}
    password: ${ATP_EMAIL_PASSWORD}
    reply-to: no-reply@askthepeople.io
    jwt: anEmailJwt
    confirmation-url: ${http://localhost:8080/confirm/email?token=}

---

spring:
    profiles: test
    application:
          name: atp-api
    datasource:
        url: ${ATP_DB_URL}
        username: ${ATP_DB_USER}
        password: ${ATP_DB_PASSWORD}

---

spring:
    profiles: prod
    application:
          name: atp-api
    datasource:
        url: ${ATP_DB_URL}
        username: ${ATP_DB_USER}
        password: ${ATP_DB_PASSWORD}
jwt:
     secret: ${ATP_JWT_APPSECRET}
     web.secret: ${ATP_JWT_WEBSECRET}
     trade.secret: ${ATP_JWT_TRADESECRET}
fcm.serverkey: ${ATP_FCM_SERVERKEY}
email:
  host: ${ATP_EMAIL_HOST}
  user: ${ATP_EMAIL_USER}
  password: ${ATP_EMAIL_PASSWORD}
  reply-to: no-reply@askthepeople.io
  jwt: ${ATP_EMAIL_JWT}
  confirmation-url: ${ATP_EMAIL_CONFIRMATION_URL}