spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/atp
        username: atpuser
        password: askthepeople
        driver-class-name: org.postgresql.Driver
    jackson:
        serialization.write_dates_as_timestamps: false
        mapper.default-view-inclusion: true
    jpa:
      show-sql: false

jwt.secret: ${ATP_JWT_APPSECRET:thisissecret}
jwt.web.secret: ${ATP_JWT_WEBSECRET:alocaljwtsecret}

api.version: @project.version@

fcm.serverkey: ${ATP_FCM_SERVERKEY:void}

email:
  host: ${ATP_EMAIL_HOST}
  user: ${ATP_EMAIL_USER}
  password: ${ATP_EMAIL_PASSWORD}
  reply-to: no-reply@askthepeople.io
  jwt: ${ATP_EMAIL_JWT}
  confirmation-url: ${ATP_EMAIL_CONFIRMATION_URL:http://localhost:8080/confirm/email?token=}

---

spring:
    profiles: prod
    datasource:
        url: ${ATP_DB_URL}
        username: ${ATP_DB_USER}
        password: ${ATP_DB_PASSWORD}