ALTER TABLE trade_plan ADD COLUMN balance_perc DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE trade_plan ADD COLUMN start_date TIMESTAMPTZ;
ALTER TABLE trade_plan ADD COLUMN last_action_date TIMESTAMPTZ;
ALTER TABLE trade_plan ADD COLUMN runs_done INT NOT NULL DEFAULT 0;